### ISSUE TITLE
wtf is wrong with the tests

### ISSUE THREAD

**Issue by Flaque** [Flaque/quirk#71]
# Overview

Something's wrong with the tests. I'm pretty sure it's something to do with `*.json` files, since the commit that introduced them into the codepath of the tests is where things start breaking. 

```
 FAIL  src/sanitize.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/evanconrad/dev/src/github.com/Flaque/quirk/node_modules/expo/build/environment/validate.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import {
                                                                                                    ^

    SyntaxError: Unexpected token {

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)
      at Object.<anonymous> (node_modules/expo/build/Expo.js:278:1)
``` 

At the moment, this is blocking #42

**Comment by Flaque** [comment]
Fixes on the `fix-tests` branch

**Comment by Flaque** [comment]
## Update
It's definitely because of the json, commenting out the imports makes the tests pass:
```
import { Localization } from "expo";
import i18n from "i18n-js";
// import en from "./locals/en.json";
// import fr from "./locals/fr.json";

i18n.fallbacks = true;
i18n.translations = {};
i18n.locale = Localization.locale;

export default i18n;
```

Pretty sure the error message is a red herring.

**Comment by Flaque** [comment]
# Update

Here's some really weird stuff. If you add the following to the top of `sanitize.test.ts`, _both_ tests will fail with the above error:

```js
import en from "./locals/en.json";
console.log(en);
```

**Comment by Flaque** [comment]
# Final Update

I fixed it, we were supposed to use the `jest-expo` preset. 🤷‍♀️
